import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from 'next/dynamic'
const HomeContainer = dynamic(() => import('../features/home/components/HomeContainer'), {
  ssr: false,
})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer />
    </div>
  );
};

export default Home;
